<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<?php
/**
 * @var \Modules\ExchangeRate\Block\ExchangeRateBlock $block
 */
?>

<?php
$arrContextOptions=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);

$url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_FAILONERROR, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 15);
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$res = curl_exec($ch);
curl_close($ch);

$new = simplexml_load_string($res);
$con = json_encode($new);
$data = json_decode($con, true);

?>
<?php
// HashMap chuyển đơn vị tiền tệ sang tên quốc gia không viết hoa chữ cái đầu
$country = [
    'AUD' => 'au',
    'CAD' => 'ca',
    'CHF' => 'dk',
    'CNY' => 'cn',
    'DKK' => 'dk',
    'EUR' => 'eu',
    'GBP' => 'gb',
    'HKD' => 'hk',
    'INR' => 'in',
    'JPY' => 'jp',
    'KRW' => 'kr',
    'KWD' => 'kw',
    'MYR' => 'my',
    'NOK' => 'no',
    'RUB' => 'ru',
    'SAR' => 'sa',
    'SEK' => 'se',
    'SGD' => 'sg',
    'THB' => 'th',
    'USD' => 'us'
];
?>

<h3 class="text-center"><b>Bảng quy đổi tiền tệ Vietcombank <?= $data['DateTime'] ?><b></h3>
<div class="link-currency">
    <a href="#currency">Currency<</a>
</div>
<table class="table" id="currency" style="width: 100%">
    <thead>
    <tr>
        <th scope="col"><h5>STT</h5></th>
        <th scope="col"><h5>Mã</h5></th>
        <th scope="col"><h5>Tên</h5></th>
        <th scope="col"><h5>Giá mua</h5></th>
        <th scope="col"><h5>Giá bán</h5></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['Exrate'] as $k => $currency): ?>
        <?php $attributes = $currency['@attributes'];
        $currencyCode = $attributes['CurrencyCode'];
        $countryName = $country[$currencyCode];
        $imageLink = "https://www.worldatlas.com/r/w236/img/flag/{$countryName}-flag.jpg";
        ?>
        <tr>
            <th scope="row"><h5><?= $k + 1 ?></h5></th>
            <td style="font-size: 1.25rem;">
                <img src="<?= $imageLink ?>" style="width: 25px; height: 15px;">
                <?= $currency['@attributes']['CurrencyCode'] ?>
            </td>
            <td><h5><?= $attributes['CurrencyName'] ?></h5></td>
            <td><h5><?= $attributes['Buy'] ?></h5></td>
            <td><h5><?= $attributes['Sell'] ?></h5></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    table, tr, th, td {
        background-color: #F0F0F0;
        border: 1px solid gray;
        border-collapse: collapse;
        text-align: center;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }
    th {
        background-color: #55A516;
        color: #ffffff;
    }
    .link-currency > a {
        text-decoration: none;
        background-color: #badc58;
        color: #ffffff;
        position: fixed;
        border-radius: 5px 0px 0px 5px;
        right: 0px;
        top: 200px;
        font-size: 18px;
        font-weight: bold;
        padding: 10px 10px 10px 5px;
        width: 100px;
        z-index: 2;
    }
    .link-currency > a:hover {
        background-color: #f1c40f;
    }
</style>
